---
interfaces:
    - name: GigabitEthernet1/0
      description: "WAN|1G|R2|Gi1/0"
      address: 172.31.254.0/31
      ospf: true
    - name: GigabitEthernet2/0
      description: "WAN|1G|R3|Gi1/0"
      address: 172.31.254.2/31
      ospf: true
    - name: GigabitEthernet3/0
      description: "WAN|1G|R4|Gi1/0"
      address: 172.31.254.6/31
      ospf: true
  ##
    - name: Ethernet6/0
      address: 172.31.254.10/31
      description: "WAN|1G|R5|Gi6/0"
      remote_asn: 400065100
      ebgp_enabled: true
    - name: Ethernet6/1
      address: 172.31.254.16/31
      description: "WAN|1G|R6|Gi6/0"
      remote_asn: 400065100
      ebgp_enabled: true
    - name: Ethernet6/2
      address: 172.31.254.20/31
      description: "WAN|1G|R7|Gi2/0"
      remote_asn: 400065200
      ebgp_enabled: true
